Item.create(
  [
    {
      name: "aaaa",
      explain: "aaaaaaaaa",
      category_id: 18,
      delivery_cost_id: 1,
      delivery_date_id: 1,
      delivery_way_id: 1,
      prefecture_id: 1,
      price: 1000,
      buyer_id: 1,
      seller_id: 2,
    },
    {
      name: "bbbb",
      explain: "bbbbbbbbb",
      category_id: 18,
      delivery_cost_id: 2,
      delivery_date_id: 2,
      delivery_way_id: 2,
      prefecture_id: 2,
      price: 2000,
      buyer_id: 2,
      seller_id: 1,
    },
    {
      name: "cccc",
      explain: "ccccccccc",
      category_id: 19,
      delivery_cost_id: 1,
      delivery_date_id: 3,
      delivery_way_id: 3,
      prefecture_id: 3,
      price: 3000,
      buyer_id: 1,
    },
    {
      name: "dddd",
      explain: "ddddddddd",
      category_id: 20,
      delivery_cost_id: 2,
      delivery_date_id: 1,
      delivery_way_id: 4,
      prefecture_id: 4,
      price: 4000,
      seller_id: 1,
    },
    {
      name: "eeee",
      explain: "eeeeeeeee",
      category_id: 21,
      delivery_cost_id: 2,
      delivery_date_id: 2,
      delivery_way_id: 5,
      prefecture_id: 5,
      price: 5000,
      seller_id: 3,
    },
    {
      name: "ffff",
      explain: "fffffffff",
      category_id: 46,
      delivery_cost_id: 2,
      delivery_date_id: 3,
      delivery_way_id: 6,
      prefecture_id: 6,
      price: 6000,
      buyer_id: 2,
      seller_id: 3,
    },
    {
      name: "gggg",
      explain: "ggggggggg",
      category_id: 46,
      delivery_cost_id: 1,
      delivery_date_id: 1,
      delivery_way_id: 7,
      prefecture_id: 7,
      price: 7000,
      buyer_id: 3,
    },
    {
      name: "hhhh",
      explain: "hhhhhhhhh",
      category_id: 47,
      delivery_cost_id: 2,
      delivery_date_id: 3,
      delivery_way_id: 8,
      prefecture_id: 8,
      price: 8000,
      seller_id: 3,
    },
    {
      name: "iiii",
      explain: "iiiiiiiii",
      category_id: 48,
      delivery_cost_id: 1,
      delivery_date_id: 3,
      delivery_way_id: 3,
      prefecture_id: 9,
      price: 9000,
      seller_id: 2,
    },
    {
      name: "jjjj",
      explain: "jjjjjjjjj",
      category_id: 49,
      delivery_cost_id: 1,
      delivery_date_id: 2,
      delivery_way_id: 4,
      prefecture_id: 10,
      price: 10000,
      buyer_id: 2,
    }
  ]
)